config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :documents
  resources :phases
  resources :summaries
  resources :departments

  root 'summaries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/summary.rb
class Summary < ApplicationRecord
	has_many :phases
	has_many :summary_users
	has_many :users, through: :summary_users
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :edit, :update, :destroy]

  # GET /summaries
  # GET /summaries.json
  def index
    @summaries = Summary.all
  end

  # GET /summaries/1
  # GET /summaries/1.json
  def show
  end

  # GET /summaries/new
  def new
    @summary = Summary.new
  end

  # GET /summaries/1/edit
  def edit
  end

  # POST /summaries
  # POST /summaries.json
  def create
    @summary = Summary.new(summary_params)

    respond_to do |format|
      if @summary.save
        format.html { redirect_to @summary, notice: 'Summary was successfully created.' }
        format.json { render :show, status: :created, location: @summary }
      else
        format.html { render :new }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /summaries/1
  # PATCH/PUT /summaries/1.json
  def update
    respond_to do |format|
      if @summary.update(summary_params)
        format.html { redirect_to @summary, notice: 'Summary was successfully updated.' }
        format.json { render :show, status: :ok, location: @summary }
      else
        format.html { render :edit }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summaries/1
  # DELETE /summaries/1.json
  def destroy
    @summary.destroy
    respond_to do |format|
      format.html { redirect_to summaries_url, notice: 'Summary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_summary
      @summary = Summary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summary_params
      params.require(:summary).permit(:description, :resolution, :starting_day, :finishing_day)
    end
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/summaries/_form.html.erb
<%= form_for(summary) do |f| %>
  <% if summary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

      <ul>
      <% summary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :resolution %>
    <%= f.number_field :resolution %>
  </div>

  <div class="field">
    <%= f.label :starting_day %>
    <%= f.datetime_select :starting_day %>
  </div>

  <div class="field">
    <%= f.label :finishing_day %>
    <%= f.datetime_select :finishing_day %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/summaries/edit.html.erb
<h1>Editing Summary</h1>

<%= render 'form', summary: @summary %>

<%= link_to 'Show', @summary %> |
<%= link_to 'Back', summaries_path %>

app/views/summaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Summaries</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Resolution</th>
      <th>Starting day</th>
      <th>Finishing day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @summaries.each do |summary| %>
      <tr>
        <td><%= summary.description %></td>
        <td><%= summary.resolution %></td>
        <td><%= summary.starting_day %></td>
        <td><%= summary.finishing_day %></td>
        <td><%= link_to 'Show', summary %></td>
        <td><%= link_to 'Edit', edit_summary_path(summary) %></td>
        <td><%= link_to 'Destroy', summary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Summary', new_summary_path %>

app/views/summaries/new.html.erb
<h1>New Summary</h1>

<%= render 'form', summary: @summary %>

<%= link_to 'Back', summaries_path %>

app/views/summaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @summary.description %>
</p>

<p>
  <strong>Resolution:</strong>
  <%= @summary.resolution %>
</p>

<p>
  <strong>Starting day:</strong>
  <%= @summary.starting_day %>
</p>

<p>
  <strong>Finishing day:</strong>
  <%= @summary.finishing_day %>
</p>

<%= link_to 'Edit', edit_summary_path(@summary) %> |
<%= link_to 'Back', summaries_path %>