config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :documents
  resources :phases
  resources :summaries
  resources :departments

  root 'summaries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :set_phase, only: [:show, :edit, :update, :destroy]

  # GET /phases
  # GET /phases.json
  def index
    @phases = Phase.all
  end

  # GET /phases/1
  # GET /phases/1.json
  def show
  end

  # GET /phases/new
  def new
    @phase = Phase.new
  end

  # GET /phases/1/edit
  def edit
  end

  # POST /phases
  # POST /phases.json
  def create
    @phase = Phase.new(phase_params)

    respond_to do |format|
      if @phase.save
        format.html { redirect_to @phase, notice: 'Phase was successfully created.' }
        format.json { render :show, status: :created, location: @phase }
      else
        format.html { render :new }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phases/1
  # PATCH/PUT /phases/1.json
  def update
    respond_to do |format|
      if @phase.update(phase_params)
        format.html { redirect_to @phase, notice: 'Phase was successfully updated.' }
        format.json { render :show, status: :ok, location: @phase }
      else
        format.html { render :edit }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1
  # DELETE /phases/1.json
  def destroy
    @phase.destroy
    respond_to do |format|
      format.html { redirect_to phases_url, notice: 'Phase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phase
      @phase = Phase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phase_params
      params.require(:phase).permit(:name, :summary_id)
    end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_form.html.erb
<%= form_for(phase) do |f| %>
  <% if phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
      <% phase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :summary_id %>
    <%= f.text_field :summary_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phases/edit.html.erb
<h1>Editing Phase</h1>

<%= render 'form', phase: @phase %>

<%= link_to 'Show', @phase %> |
<%= link_to 'Back', phases_path %>

app/views/phases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phases</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phases.each do |phase| %>
      <tr>
        <td><%= phase.name %></td>
        <td><%= phase.summary %></td>
        <td><%= link_to 'Show', phase %></td>
        <td><%= link_to 'Edit', edit_phase_path(phase) %></td>
        <td><%= link_to 'Destroy', phase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phase', new_phase_path %>

app/views/phases/new.html.erb
<h1>New Phase</h1>

<%= render 'form', phase: @phase %>

<%= link_to 'Back', phases_path %>

app/views/phases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phase.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @phase.summary %>
</p>

<%= link_to 'Edit', edit_phase_path(@phase) %> |
<%= link_to 'Back', phases_path %>